"""updated  users

Revision ID: 728cdf3b1f68
Revises: 9c0948c54eba
Create Date: 2025-06-16 00:24:32.633974

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '728cdf3b1f68'
down_revision: Union[str, None] = '9c0948c54eba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('users', 'email',
#                existing_type=sa.VARCHAR(length=255),
#                nullable=False)
#     op.alter_column('users', 'password',
#                existing_type=sa.VARCHAR(length=100),
#                nullable=False)
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('users', 'password',
#                existing_type=sa.VARCHAR(length=100),
#                nullable=True)
#     op.alter_column('users', 'email',
#                existing_type=sa.VARCHAR(length=255),
#                nullable=True)
#     # ### end Alembic commands ###
def upgrade():
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("email",
            existing_type=sa.String(length=255),
            nullable=False
        )

def downgrade():
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("email",
            existing_type=sa.String(length=255),
            nullable=True
        )